#!/bin/bash
function do_it() {
  rsync --exclude ".git/" --exclude ".DS_Store" --exclude "init/" --exclude "script/" --exclude "restart-bt.sh" --exclude "see-you.sh" --exclude "README.md" -av .. ~
}
if [ "$1" == "--force" -o "$1" == "-f" ]; then
  do_it
else
  read -p "This may overwrite existing files in your home directory. Are you sure? (y/n) " -n 1
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    do_it
  fi
fi
unset do_it
source ~/.bash_profile
